# Generated by Django 5.1.2 on 2024-10-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='template_code',
            field=models.TextField(default=''),
        ),
    ]
